name: Create Repository from Issue

on:
  issues:
    types: [opened]

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue form data
        id: form_data
        run: |
          echo "REPO_NAME=$(echo '${{ github.event.issue.body }}' | grep 'Repository Name' | cut -d ':' -f 2 | xargs)" >> $GITHUB_ENV
          echo "VISIBILITY=$(echo '${{ github.event.issue.body }}' | grep 'Visibility' | cut -d ':' -f 2 | xargs)" >> $GITHUB_ENV

      - name: Create repository via API
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.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 }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/YOUR_ORG/repos \
            -d "{\"name\": \"$REPO_NAME\", \"private\": $( [ \"$VISIBILITY\" = 'Private' ] && echo true || echo false )}"

        env:
          REPO_NAME: ${{ env.REPO_NAME }}
          VISIBILITY: ${{ env.VISIBILITY }}
